import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "./database.types";

const DEFAULT_SUPABASE_URL = "https://jmgfabzsgrukrzpnuhux.supabase.co";
const DEFAULT_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_eCJHRbegR3FVk1Hbu3Kbgw_aMoMwvNb";

const url = import.meta.env.VITE_SUPABASE_URL || DEFAULT_SUPABASE_URL;
const key = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || DEFAULT_SUPABASE_PUBLISHABLE_KEY;

export const supabase = createClient(url, key);

/**
 * The same client, statically typed against the schema generated by
 * `supabase gen types typescript --linked` (database.types.ts — regenerate
 * with that command after a migration changes a table this file reads).
 *
 * Only the data-mapping layer imports this one (admin.ts, content.ts,
 * trainer.ts, team.ts) — the files that used to cast a `.select()` result to
 * `any` before manually reshaping it into a domain type. Typed, that reshaping
 * is checked against the real row shape instead: a column renamed in a
 * migration becomes a compile error here rather than a silent `undefined` in
 * production.
 *
 * The rest of the app keeps importing plain `supabase` on purpose. Widening
 * this to every call site would also retype every `.rpc()` argument, and
 * `supabase gen types` does not carry nullability for function *parameters*
 * the way it does for table columns — every optional argument comes back
 * without `| null` even where the underlying function's `DEFAULT NULL` accepts
 * it, which would force real call sites to change how they call a function
 * that has not changed at all. That is a fight with the generator, not a
 * correctness fix, so it is left alone outside the four files that actually
 * had an `any` to remove.
 */
export const typedSupabase: SupabaseClient<Database> = supabase as SupabaseClient<Database>;
