import { BookOpenCheck, CheckCircle2, Database, HeartPulse, Layers3, Scale, ShieldCheck, UsersRound } from "lucide-react";
import PageShell from "../components/PageShell";


export default function AboutPage() {
  return <PageShell>
    <section className="page-hero"><div className="container narrow"><span className="eyebrow">عن بلو ريهاب</span><h1>منصة واحدة لمسارين مختلفين، دون خلط البيانات أو الغرض</h1><p>يحتاج المصاب إلى رعاية ومتابعة آمنة، ويحتاج الطالب إلى تعلم وقياس تقدم. تجمع المنصة المسارين في حساب موحد مع فصل وظيفي وصلاحيات دقيقة.</p></div></section>
    <section className="section"><div className="container about-intro-grid"><div><span className="kicker">المشكلة التي نعالجها</span><h2>التجربة المبعثرة تضعف المتابعة</h2><p>عندما يكون الحجز في قناة، والخطة في ملف، والتمارين في رسائل، يصعب معرفة النسخة الصحيحة أو قياس الالتزام. وفي التدريب، يؤدي فصل التسجيل والمحتوى والحضور والشهادة إلى العمل اليدوي والأخطاء.</p><p>بلو ريهاب تبني سجلاً واحداً لكل رحلة، بحيث يرتبط كل إجراء بمستخدم ودور ووقت وعنصر واضح.</p></div><div className="about-paths"><article><HeartPulse /><h3>المسار العلاجي</h3><p>طلب جلسة، ملف صحي، تقييم، خطة، تمارين، سجل التزام ومراجعات.</p></article><article><BookOpenCheck /><h3>المسار التدريبي</h3><p>تسجيل، وحدات، حضور، تقدم، تقييم وشهادة وفق شروط.</p></article></div></div></section>
    <section className="section surface-section"><div className="container"><header className="section-heading centered"><span className="kicker">مبادئ المنتج</span><h2>الوضوح قبل الإبهار</h2></header><div className="principles-grid"><article><Scale /><h3>لا ضمان لنتيجة علاجية</h3><p>نعرض خطوات الرعاية ومؤشرات المتابعة دون وعود مطلقة أو صياغة تضخم النتائج.</p></article><article><ShieldCheck /><h3>أقل صلاحية لازمة</h3><p>يرى المستخدم فقط ما يحتاجه لدوره، ويُسجل الوصول للبيانات الحساسة.</p></article><article><Layers3 /><h3>فصل المسارين</h3><p>ملف العلاج مستقل عن ملف التدريب مع إمكانية الجمع بينهما في الحساب نفسه لاحقاً.</p></article><article><UsersRound /><h3>قرار بشري مسؤول</h3><p>لا تستبدل المنصة حكم الأخصائي، ولا تنشر ملف مقدم خدمة قبل الاعتماد.</p></article></div></div></section>
    <section className="section"><div className="container readiness-page"><div><span className="kicker">الحالة الحالية</span><h2>ما يعمل الآن وما ينتظر قراراً خارجياً</h2><p>اكتمال الواجهة لا يعني الادعاء بأن مزوداً خارجياً مفعّل. لذلك نفصل بين جاهزية النظام وجاهزية التعاقد.</p></div><div className="readiness-columns"><section><h3><CheckCircle2 /> جاهز في النسخة</h3><ul><li>كتالوج الخدمات والدورات.</li><li>مسار الحجز والتسجيل كعرض تشغيلي.</li><li>نماذج لوحات جميع الأدوار.</li><li>فصل بيانات كل مستخدم وصلاحيات حسب الدور.</li><li>تخزين خاص لمرفقات الاعتماد المهني.</li><li>تصميم عربي متجاوب ودعم تقليل الحركة.</li></ul></section><section><h3><Database /> يحتاج إعداد جهة مزودة</h3><ul><li>رسائل رمز التحقق SMS.</li><li>بوابة الدفع والاسترداد.</li><li>اجتماعات الفيديو الآمنة.</li><li>البريد والواتساب والإشعارات النصية.</li><li>العنوان والفرع وقنوات الدعم الرسمية.</li><li>رفع المريض لملفاته الطبية.</li><li>المراجعة الطبية والقانونية النهائية.</li></ul></section></div></div></section>
  </PageShell>;
}



